version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: api-gateway
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
      
  auth:
    build:
      context: ../AuthService
      dockerfile: Dockerfile
    container_name: auth
    hostname: auth
    ports:
      - "4000:4000"
      
  product:
    build:
      context: ../ProductService
      dockerfile: Dockerfile
    hostname: product
    container_name: product
    ports:
      - "5000:5000"
    volumes:
      - ../source:/usr/src/app
      
  order:
    build:
      context: ../OrderService
      dockerfile: Dockerfile
    hostname: order
    container_name: order
    ports:
      - "5001:5001"

  feedback:
    build:
      context: ../FeedbackService
      dockerfile: Dockerfile
    hostname: feedback
    container_name: feedback
    ports:
      - "5002:5002"
      
  admin:
    build:
      context: ../AdminService
      dockerfile: Dockerfile
    hostname: admin
    container_name: admin
    ports:
      - "8000:8000"
