version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: api-gateway
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt/live/shoptaiche.gokag.id.vn:/etc/nginx/certificates
      
  auth:
    build:
      context: ../AuthService
      dockerfile: Dockerfile
    container_name: auth
    hostname: auth
    ports:
      - "4000:4000"
    environment:
      - DATABASE_POSTGRE=postgresql://default:root@13.250.111.7:5432/shoptaiche
      - DATABASE_MONGODB=mongodb+srv://sorak:rUWsvoIAzOBllNzn@cluster0.vxj0hf8.mongodb.net/shoptaiche
      - NODE_ENV=development
      
  product:
    build:
      context: ../ProductService
      dockerfile: Dockerfile
    hostname: product
    container_name: product
    ports:
      - "5000:5000"
    environment:
      - DATABASE_POSTGRE=postgresql://default:root@13.250.111.7:5432/shoptaiche
      - DATABASE_MONGODB=mongodb+srv://sorak:rUWsvoIAzOBllNzn@cluster0.vxj0hf8.mongodb.net/shoptaiche
      - NODE_END=development
 
  order:
    build:
      context: ../OrderService
      dockerfile: Dockerfile
    hostname: order
    container_name: order
    ports:
      - "5001:5001"
    environment:
      - DATABASE_POSTGRE=postgresql://default:root@13.250.111.7:5432/shoptaiche
      - DATABASE_MONGODB=mongodb+srv://sorak:rUWsvoIAzOBllNzn@cluster0.vxj0hf8.mongodb.net/shoptaiche
      - NODE_END=development

  feedback:
    build:
      context: ../FeedbackService
      dockerfile: Dockerfile
    hostname: feedback
    container_name: feedback
    ports:
      - "5002:5002"
    environment:
      - DATABASE_POSTGRE=postgresql://default:root@13.250.111.7:5432/shoptaiche
      - DATABASE_MONGODB=mongodb+srv://sorak:rUWsvoIAzOBllNzn@cluster0.vxj0hf8.mongodb.net/shoptaiche
      - NODE_END=development

  admin:
    build:
      context: ../AdminService
      dockerfile: Dockerfile
    hostname: admin
    container_name: admin
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_USER=default
      - POSTGRES_HOST=13.250.111.7:5432
      - POSTGRES_PASSWORD=root
      - POSTGRES_DATABASE=shoptaiche
      - JWT_SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      - JWT_REFRESH_SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e721312
      - JWT_ALGORITHM=HS256
      - MJ_APIKEY_PUBLIC=05c36ce8b3b65779ccc70e25a1bc0ce8
      - MJ_APIKEY_PRIVATE=54de754f633f280ed900ee03c7f73a86
